version: '3.8'
services: 
    nsfw-api:
        environment:
            - PORT=5000
        build: ./compose/nsfw-api/
        ports:
            - 5000:5000
        volumes:
            - ./web:/opt/web
        networks:
            - webnet
            
    dj3:
        container_name: dj3
        build:
            context: .
            target: development
            dockerfile : ./compose/nestjs/Dockerfile
        volumes:
        - .:/usr/src/app
        - /usr/src/app/node_modules
        ports:
        - ${SERVER_PORT}:${SERVER_PORT}
        command: npm run start:dev
        networks:
            - webnet
        env_file:
            - .env
        links:
            - postgres
            - redis
        depends_on:
            - redis
            - postgres
    redis:
        container_name: redis
        image: redis:5
        networks:
            - webnet

    postgres:
        container_name: postgres
        image: postgres:12
        
        networks:
            - webnet
        environment:
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_USER: ${DB_USERNAME}
            POSTGRES_DB: ${DB_DATABASE_NAME}
            PG_DATA: /var/lib/postgresql/data
        ports:
            - ${DB_PORT}:${DB_PORT}
        volumes:
            - pgdata:/var/lib/postgresql/data
networks:
    webnet:
volumes:
    pgdata:
